name: fuegosoft_ayuda_services
description: Ayuda App is an app that will help customers to find workers around the community with ease

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_core: ^0.4.0+1
  firebase_analytics: ^3.0.1
  cloud_firestore: ^0.11.0+2
  firebase_auth: ^0.11.1
  google_sign_in: ^4.0.1+3
  flutter_facebook_login: 
    git: https://github.com/lequanghiep74/flutter_facebook_login
  rxdart: ^0.22.0
  http: ^0.12.0+2
  http_retry: ^0.1.1+3
  flutter_bloc: ^0.17.0
  hydrated_bloc: ^0.2.1
  equatable: ^0.2.6
  date_format: ^1.0.6
  flutter_datetime_picker: ^1.2.1
  google_maps_flutter:
      git:
        url: git://github.com/awazgyawali/plugins/
        path: packages/google_maps_flutter
        ref: google_maps_polyline
  get_it: ^1.0.3+1
  provider: ^2.0.1+1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/bg/bg.png
    - assets/bg/bg2.png
    - assets/logo/logo.png
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/icon_buttons/icon_button_settings.png
    - assets/drawer_header/drawer_header_bg.png
    - assets/profile/girl.png
    - assets/profile/man.png
    - assets/google_maps_icon/icons-gps.png
    - assets/google_maps_icon/icons-filter-map.png
    - assets/settings/profile.png
    - assets/settings/promo.png
    - assets/settings/history.png
    - assets/settings/info.png
    - assets/settings/contacts.png
    - assets/settings/setting.png
    - assets/settings/worker.png
    - assets/settings/logout.png
    - assets/settings/plus.png
    - assets/settings/share-symbol.png
    - assets/settings/layers.png
    - assets/settings/cancel.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Aprilea
      fonts:
        - asset: assets/fonts/Aprilea.ttf
    - family: Lemon
      fonts:
        - asset: assets/fonts/Lemon-Regular.ttf
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo-Regular.ttf
    - family: Black Han Sans
      fonts:
        - asset: assets/fonts/BlackHanSans-Regular.ttf
    - family: Ramabhadra
      fonts:
        - asset: assets/fonts/Ramabhadra-Regular.ttf
    - family: Gafata
      fonts:
        - asset: assets/fonts/Gafata-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
